server:
  port: 8080
spring:
  application:
    name: eureka-client #???????????
eureka:
  client:
    server-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: peer3
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true #??ip
    lease-renewal-interval-in-seconds: 10 #????